apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mlapi
  name: mlapi
  labels:
    app: mlapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
        - name: mlapi
          image: astrobase/mlapi
          resources:
            requests:
              memory: "5Gi"
              cpu: "1000m"
            limits:
              memory: "13Gi"
              cpu: "2000m"
