apiVersion: v1
kind: Service
metadata:
  namespace: mlapi
  labels:
    app: mlapi
  name: mlapi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: mlapi
  type: LoadBalancer
