apiVersion: v1
kind: Namespace
metadata:
  name: mlapi
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mlapi
  labels:
    app: mlapi
  name: mlapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
        - image: astrobase/mlapi
          name: mlapi
          resources:
            requests:
              memory: "1GiB"
              cpu: "500m"
            limits:
              memory: "2GiB"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: mlapi
  labels:
    app: mlapi
  name: mlapi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: mlapi
  type: LoadBalancer
